### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TritAlpha** [NBISweden/workshop-scRNAseq#13]
Hello. I recently encountered a problem and I hope to get help. I didn’t understand the meaning of **"PECAM1|PF4"** very well when I ran this code. I tried to search for relevant information but did not find a satisfactory answer. I hope to get help. grateful!

Percentage hemoglobin genes - includes all genes starting with HB except HBP.
alldata <- PercentageFeatureSet(alldata, "^HB[^(P)]", col.name = "percent_hb")
alldata <- PercentageFeatureSet(alldata, "PECAM1|PF4", col.name = "percent_plat")

**Comment by asabjorklund** [comment]
Sorry @CJSCI666, for the late reply, PECAM1, PF4 are two platelet marker genes. So we are just trying to identify platelet cells by identifying droplets with high relative expression of those 2 genes.

**Comment by TritAlpha** [comment]
您的信件我已经收到。 This is an automatic reply, confirming that your e-mail was received.Thank you
