### ISSUE TITLE
Is it appropriate to use doubletFinder to multiple multiple samples?

### ISSUE THREAD

**Issue by zhouzhendiao** [NBISweden/workshop-scRNAseq#19]
I quoted suggestions in [doubletFinder github](https://github.com/chris-mcginnis-ucsf/DoubletFinder) here:

> Do not apply DoubletFinder to aggregated scRNA-seq data representing multiple distinct samples (e.g., multiple 10X lanes). For example, if you run DoubletFinder on aggregated data representing WT and mutant cell lines sequenced across different 10X lanes, artificial doublets will be generated from WT and mutant cells, which cannot exist in your data. These artificial doublets will skew results. Notably, it is okay to run DoubletFinder on data generated by splitting a single sample across multiple 10X lanes.

In my opinion, It‘s not recommended to use douletFinder on multiple samlples. But in the chaper [Seurat_qc](https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/seurat/seurat_01_qc.html),  function `doubletFinder_v3` was using on a merged PBMC data with both covid samples and healthy samples. Would it generate artificial doublets mentioned before?

**Comment by asabjorklund** [comment]
You are correct, it should be done per sample, for now we only have a comment about it in the text but we are planning to change the exercise to run it per sample.

**Comment by zhouzhendiao** [comment]
> You are correct, it should be done per sample, for now we only have a comment about it in the text but we are planning to change the exercise to run it per sample.

OK, I got it. Thanks for replying.
