### ISSUE TITLE
Bug in scanpy/mnnpy in lesson 3

### ISSUE THREAD

**Issue by Benfeitas** [NBISweden/workshop-scRNAseq#9]
I'm finding [this bug](https://github.com/chriscainx/mnnpy/issues/30#issue-545317818) when running mnn in lesson 3.  Installing numba 0.45 didn't solve the issue. Installing  llvmlite=0.30.0 and numba=0.46 didn't solve either

**Comment by Benfeitas** [comment]
Closing this as it seems it is an isolated event and others can run everything normally.

**Comment by fxgaldos** [comment]
Hello,

I would recommend reopening this. I have also encountered the same problem and installing earlier versions of llvmlite or Numba did not solve the problem.
